/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['label[_ngcontent-%COMP%] {\n    display: inline-block;\n    width: 3em;\n    margin: .5em 0;\n    color: #607D8B;\n    font-weight: bold;\n}\ninput[_ngcontent-%COMP%] {\n    height: 2em;\n    font-size: 1em;\n    padding-left: .4em;\n}\nbutton[_ngcontent-%COMP%] {\n    margin-top: 20px;\n    font-family: Arial;\n    background-color: #eee;\n    border: none;\n    padding: 5px 10px;\n    border-radius: 4px;\n    cursor: pointer; cursor: hand;\n}\nbutton[_ngcontent-%COMP%]:hover {\n    background-color: #cfd8dc;\n}\nbutton[_ngcontent-%COMP%]:disabled {\n    background-color: #eee;\n    color: #ccc;\n    cursor: auto;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd29yay9wcmovY29kZS93ZWIvbGlmZWRlZmVuZGVyL2xpZmVkZWZlbmRlci1tb2JpbGUvbW9iaWxlL3NyYy9hcHAvbWVudS1kZXRhaWwuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi93b3JrL3Byai9jb2RlL3dlYi9saWZlZGVmZW5kZXIvbGlmZWRlZmVuZGVyLW1vYmlsZS9tb2JpbGUvc3JjL2FwcC9tZW51LWRldGFpbC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
