/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.help-infor[_ngcontent-%COMP%]{\r\n    padding: .1rem .24rem;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   .title-lists[_ngcontent-%COMP%]{\r\n    color: #333;\r\n    font-size: .28rem;\r\n    line-height: 2.2;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   .sub-title-lists[_ngcontent-%COMP%]{\r\n    color: #444;\r\n    font-size: .26rem;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{\r\n    font-size: .26rem;\r\n    color: #666;\r\n    line-height: 1.8;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   .help-img[_ngcontent-%COMP%]{\r\n    padding-top: .16rem;\r\n    text-align: center;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd29yay9wcmovY29kZS93ZWIvbGlmZWRlZmVuZGVyL2xpZmVkZWZlbmRlci1tb2JpbGUvbW9iaWxlL3NyYy9hcHAvY29tcG9uZW50L2hlbHAvaGVscC1kZXRhaWwuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi93b3JrL3Byai9jb2RlL3dlYi9saWZlZGVmZW5kZXIvbGlmZWRlZmVuZGVyLW1vYmlsZS9tb2JpbGUvc3JjL2FwcC9jb21wb25lbnQvaGVscC9oZWxwLWRldGFpbC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
