/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-result[_ngcontent-%COMP%]{\n    border-bottom: 1px solid gray;\n    border-left: 1px solid gray;\n    border-right: 1px solid gray;\n    width:195px;\n    height: 16px;\n    padding: 5px;\n    background-color: white;\n    cursor: pointer;\n}\n.search-result[_ngcontent-%COMP%]:hover {\n    color: #eee;\n    background-color: #607D8B;\n}\n#search-box[_ngcontent-%COMP%]{\n    width: 200px;\n    height: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd29yay9wcmovY29kZS93ZWIvbGlmZWRlZmVuZGVyL2xpZmVkZWZlbmRlci1tb2JpbGUvbW9iaWxlL3NyYy9hcHAvbWVudS1zZWFyY2guY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi93b3JrL3Byai9jb2RlL3dlYi9saWZlZGVmZW5kZXIvbGlmZWRlZmVuZGVyLW1vYmlsZS9tb2JpbGUvc3JjL2FwcC9tZW51LXNlYXJjaC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
