/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './help-detail.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/common';
import * as import3 from '../../../../../src/app/component/help/help-detail.component';
import * as import4 from '../../../../../src/app/service/help.service';
import * as import5 from '@angular/router';
const styles_HelpDetailComponent:any[] = [import0.styles];
export const RenderType_HelpDetailComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_HelpDetailComponent,
  data: {}
}
);
function View_HelpDetailComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'help-infor'
      ]
      ],[[
        8,
        'innerHTML',
        1
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.help.content;
    ck(v,0,0,currVal_0);
  });
}
export function View_HelpDetailComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_HelpDetailComponent_1)),
    import1.ɵdid(8192,(null as any),0,import2.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import3.HelpDetailComponent = v.component;
    const currVal_0:any = co.help;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_HelpDetailComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HelpDetailComponent_0,RenderType_HelpDetailComponent)),
    import1.ɵdid(57344,(null as any),0,import3.HelpDetailComponent,[
      import4.HelpService,
      import5.ActivatedRoute,
      import2.Location
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const HelpDetailComponentNgFactory:import1.ComponentFactory<import3.HelpDetailComponent> = import1.ɵccf('ng-component',import3.HelpDetailComponent,View_HelpDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovd29yay9wcmovY29kZS93ZWIvbGlmZWRlZmVuZGVyL2xpZmVkZWZlbmRlci1tb2JpbGUvbW9iaWxlL3NyYy9hcHAvY29tcG9uZW50L2hlbHAvaGVscC1kZXRhaWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3dvcmsvcHJqL2NvZGUvd2ViL2xpZmVkZWZlbmRlci9saWZlZGVmZW5kZXItbW9iaWxlL21vYmlsZS9zcmMvYXBwL2NvbXBvbmVudC9oZWxwL2hlbHAtZGV0YWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3dvcmsvcHJqL2NvZGUvd2ViL2xpZmVkZWZlbmRlci9saWZlZGVmZW5kZXItbW9iaWxlL21vYmlsZS9zcmMvYXBwL2NvbXBvbmVudC9oZWxwL2hlbHAtZGV0YWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovd29yay9wcmovY29kZS93ZWIvbGlmZWRlZmVuZGVyL2xpZmVkZWZlbmRlci1tb2JpbGUvbW9iaWxlL3NyYy9hcHAvY29tcG9uZW50L2hlbHAvaGVscC1kZXRhaWwuY29tcG9uZW50LnRzLkhlbHBEZXRhaWxDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiaGVscC1pbmZvclwiICpuZ0lmPVwiaGVscFwiIFtpbm5lckh0bWxdPSBoZWxwLmNvbnRlbnQ+XHJcblxyXG48L2Rpdj4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBK0Q7Ozs7SUFBMUI7SUFBckMsU0FBcUMsU0FBckM7Ozs7O0lBQUE7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7OztJQUF3QjtJQUF4QixTQUF3QixTQUF4Qjs7Ozs7SUNBQTtnQkFBQTs7OztJQUFBO0tBQUE7OztJQUFBOzs7In0=
